### ISSUE TITLE
Traceback in baseline-intermediate.

### ISSUE THREAD

**Issue by tvorogme** [goto-ru/2016-09.school-baseline#8] opened 2016-07-16 07:28 UTC
Seems like baseline-intermediate not working.

`tuple(apk_n(100))` raise `ValueError`, same with `mapk_n(100)` 

Please check it out.

**Comment by wldhx** [comment] 2016-07-16 13:10
Works for me, not enough details to reproduce.

**Comment by tvorogme** [comment] 2016-07-16 14:13
You can look  for whole traceback [here](https://github.com/xenx/2016.09-school-baseline/blob/patch-2/baseline-intermediate.ipynb).

**Comment by wldhx** [comment] 2016-07-16 15:16
I think your version of repo is out of sync with `master`. Update and retry.

**Comment by tvorogme** [comment] 2016-07-16 15:39
I have checked one more time with new clone of repo but the same error has occurred.

**Comment by wldhx** [comment] 2016-07-16 16:33
I'm inclined to say you haven't.

Try doing this with a _completely_ fresh clone without modifying it in the littlest; I have an idea of what might be wrong, and I'll tell you that one I'm sure - that is, if ^ will work properly.

**Comment by wldhx** [comment] 2016-07-17 09:33
I believe we've arrived to the conclusion it's not an upstream error, but rather user's mistake out-of-band. Therefore, closing. Reopen if you have to.

**Closed as completed by wldhx** 2016-07-17 09:33 UTC
